[project]
name = "blog-scraper"
version = "0.1.0"
description = "Pulls RSS feed from HIBF and stores in Directus CMS"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "feedparser>=6.0.11",
    "requests>=2.32.0",
    "python-dateutil>=2.9.0"
]
